# Generated by Django 4.0.4 on 2023-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_alter_deviseapis_crop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviseapis',
            name='ec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deviseapis',
            name='oc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deviseapis',
            name='ph',
            field=models.FloatField(default=0.0),
        ),
    ]
