# Generated by Django 4.0.4 on 2023-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0003_deviseapis_ec_deviseapis_oc_deviseapis_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicountthreshold',
            name='blue',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='apicountthreshold',
            name='green',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='apicountthreshold',
            name='orange',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='apicountthreshold',
            name='red',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='deviselocation',
            name='latitude',
            field=models.FloatField(default=15.3173),
        ),
        migrations.AlterField(
            model_name='deviselocation',
            name='longitude',
            field=models.FloatField(default=75.7139),
        ),
    ]
