"""
Django settings for agriculture_project_backend project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authapp',
    'agriapp',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'devise_apis',
    'reports',
    'versions',
    'razorpay_app',
    'soilmap',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agriculture_project_backend.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agriculture_project_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
       'NAME'    : os.environ.get('DB_NAME', 'myproject1'),
       'USER'    : os.environ.get('DB_USER', 'myprojectuser'),
       'PASSWORD': os.environ.get('DB_PASSWORD', ''),
       'HOST'    : os.environ.get('DB_HOST', 'localhost'),
       'PORT'    : os.environ.get('DB_PORT', ''),
   }
}

# DATABASES = {
#      'default': {
#          'ENGINE': 'django.db.backends.sqlite3',
#          'NAME': BASE_DIR / 'db.sqlite3',
#      }
# }

# ── REST Framework ──────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
}

# ── JWT Token Settings ───────────────────────────────────────────────────────
# Edit MOBILE_TOKEN_SETTINGS to change expiry values from a single place.
from datetime import timedelta
MOBILE_TOKEN_SETTINGS = {
    'ACCESS_TOKEN_LIFETIME_DAYS' : 2,    # change here to adjust access token expiry
    'REFRESH_TOKEN_LIFETIME_DAYS': 15,   # change here to adjust refresh token expiry
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(days=MOBILE_TOKEN_SETTINGS['ACCESS_TOKEN_LIFETIME_DAYS']),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=MOBILE_TOKEN_SETTINGS['REFRESH_TOKEN_LIFETIME_DAYS']),
    'ROTATE_REFRESH_TOKENS' : True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'devise_apis.mobile_serializers.MobileTokenObtainSerializer',
}

# ── DRF Spectacular (Swagger / ReDoc) ────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE': 'ArkaShine Mobile API',
    'DESCRIPTION': (
        'Complete REST API for the ArkaShine agricultural IoT platform. '
        'Supports JWT authentication, device management, sensor readings, '
        'thresholds, recommendations, and OTA firmware updates.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'name': 'ArkaShine Team'},
    'TAGS': [
        {'name': 'Auth',          'description': 'Login, token refresh, logout'},
        {'name': 'Device Types',  'description': 'List all device types with lock/unlock status'},
        {'name': 'Devices',       'description': 'User device listing and details'},
        {'name': 'API Calls',     'description': 'Sensor readings per device'},
        {'name': 'SoiLENZ',       'description': 'SoiLENZ soil sensor readings and recommendations'},
        {'name': 'SoilSparsh',    'description': 'SoilSparsh atmospheric sensor readings'},
        {'name': 'SoilLIFE',      'description': 'SoilLIFE biological sensor readings'},
        {'name': 'PHBottle',      'description': 'PHBottle pH sensor readings'},
        {'name': 'Account',       'description': 'User profile and password management'},
        {'name': 'CarbonCredits', 'description': 'Carbon credit calculation, farm analysis, and PDF report generation'},
    ],
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
}

# Carbon credit engine settings
CARBON_MARKET_RATE      = 1400.0   # ₹ per carbon credit
OPENWEATHERMAP_API_KEY  = ''        # set to fetch live weather; leave blank to use user-provided values

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

# STATIC_URL = '/static/'


# STATICFILES_DIRS = [
#     os.path.join(os.path.dirname(BASE_DIR), 'static-cdn-local')
# ]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static-cdn-local')

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '13.51.217.17',
                 'www.arkashine-innovations.com', 'arkashine-innovations.com']

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# email = 'ka36l1107@gmail.com'
# password = '123zlrpdfmdnabvahou123'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DATE_INPUT_FORMATS = ['%Y/%m/%d']

LOGIN_URL = '/'

# 300 MB upload safety
DATA_UPLOAD_MAX_MEMORY_SIZE = 314572800  # 300MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760   # 10MB (rest streams to disk)

RAZORPAY_API_KEY    = os.environ.get('RAZORPAY_API_KEY', '')
RAZORPAY_SECRET_KEY = os.environ.get('RAZORPAY_SECRET_KEY', '')
WEBHOOK_SECRET      = os.environ.get('WEBHOOK_SECRET', '')